### PR TITLE
Adding Reddit instructlab page to quicklinks

### PR DESCRIPTION
**Pull request by mairin**
SSIA

### CODE REVIEW

**Review by bjhargrave — APPROVED** [review]

**Review by lhawthorn — APPROVED** [review]
LGTM.

**Comment by bjhargrave** [comment]
Need to add Reddit to the spellcheck dictionary to make spellcheck happy.

**Comment by lhawthorn** [comment]
@bjhargrave Would you please update the dictionary? @mairin and I are doing some repo scrubbing work and would rather focus on that bit. Thank you for your consideration.

**Comment by nathan-weinberg** [comment]
Rebased and fixed dictionary

**Pull request merged**
